apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejs
  labels:
    app: {{ .Release.Name }}-nodejs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nodejs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nodejs
    spec:
      containers:
        - name: nodejs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

