apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-nodejs
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
      
