replicaCount: 1

image:
  repository: sushmita04/nodejs-app
  tag: latest
  imagePullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  type: NodePort
  port: 3000
  nodePort: 32000

